### ISSUE TITLE
Documentation mismatch for TX & OP result code

### ISSUE THREAD

**Issue by cyberluke** [lightsail-network/java-stellar-sdk#154]
Here the table shows column Error and column Code:
https://www.stellar.org/developers/guides/concepts/transactions.html

Column Code is number here.

But Java SDK returns code as string:
```response.getExtras().getResultCodes().getTransactionResultCode()```

So if it is String, then it's not Result Code from documentation, but more likley the Error (text) column, right?

WRONG!

Because here is another documentation: https://www.stellar.org/developers/horizon/reference/errors/transaction-failed.html

And it shows:
```"extras": {
    "envelope_xdr": "...",
    "result_xdr": "...",
    "result_codes": {
      "transaction": "tx_failed",
      "operations": [ "op_bad_auth" ]
    }
  }
```

Which is 3rd representation and this is nowhere documented. Here it shows you use string as result code , but you use some undocumented textual representation. Where in documentation is mentioned "tx_" and "op_" prefix? Is this rule or exception? Are there any other possible prefixes in result codes? Do you have any documentation for SDK how to handle these result codes and best practices?

**Comment by overcat** [comment]
Current users can find all possible code [here](https://github.com/stellar/go/blob/7d248ce65aa784b92bbd9a6663d5a4950dd7743e/services/horizon/internal/codes/main.go).
