### ISSUE TITLE
New soroban_readme.md for Soroban sdk usage

### ISSUE THREAD

**Issue by sreuland** [lightsail-network/java-stellar-sdk#516]
### What problem does your feature solve?
lack of high level developer focused docs to assist with rapidly writing java sdk code that invokes a soroban contract.

there are many unit tests that demonstrate separate portions of the soroban sdk usage, but a high level opinionated writeup explaining the sdk code that can invoke contracts and navigate the simulations and bump/restore aspects. 

### What would you like to see?

* a new `soroban_readme.md` which provides a 'in a nutshell' section on using the sdk to interact with soroban contracts, with a sdk code example of invoking a contract, handling simulation responses, fees, and potential restore/bump retries for expired entries.

* reuse links to existing soroban docs for all high level concepts - https://soroban.stellar.org/docs/category/fundamentals-and-concepts, avoid duplicated content.

*  add a section for `Development` , link to [Soroba#RPC](https://soroban.stellar.org/docs/reference/rpc) for explanation of the stack and how to use quickstart for local dev on standalone or futurenet network.[Quickstart#Soroban Development](https://github.com/stellar/quickstart#soroban-development)

**Comment by overcat** [comment]
We have added relevant examples at https://developers.stellar.org/docs
