### ISSUE TITLE
How to configure Friendbot for testnet network ?

### ISSUE THREAD

**Issue by sanjayhashcash** [lightsail-network/java-stellar-sdk#587]
How to configure Friendbot for testnet network ? please give me proper guide

**Comment by sanjayhashcash** [comment]
When I write contract and add address that time coming error is-->  error: Friendbot not found: Friendbot is not available on this network

**Comment by overcat** [comment]
Please check this link: https://developers.stellar.org/docs/tutorials/create-account#create-account
