### ISSUE TITLE
Base fee type mismatch

### ISSUE THREAD

**Issue by lijamie98** [lightsail-network/java-stellar-sdk#656]
The `MIN_BASE_FEE` is `int` in [AbstractTransaction.java](https://github.com/lightsail-network/java-stellar-sdk/blob/master/src/main/java/org/stellar/sdk/AbstractTransaction.java#L33) but the `setBaseFee()` is `long` in [TransactionBuilder.java.](https://github.com/lightsail-network/java-stellar-sdk/blob/master/src/main/java/org/stellar/sdk/TransactionBuilder.java#L137).

**Comment by overcat** [comment]
Hi, @lijamie98, thank you for reporting this, I will include it in the next release.
